cat ./act-1-ancient-foundations/01-socratic-awakening.md
cat ./act-1-ancient-foundations/02-platonic-shadows.md
cat ./act-1-ancient-foundations/03-confucian-harmony.md
cat ./act-1-ancient-foundations/04-nagarjuna-emptiness.md
cat ./act-1-ancient-foundations/05-zhuangzi-flow.md
cat ./act-1-ancient-foundations/06-imhotep-integration.md
cat ./act-2-medieval-synthesis/07-augustine-time.md
cat ./act-2-medieval-synthesis/08-avicenna-being.md
cat ./act-2-medieval-synthesis/09-maimonides-knowledge.md
cat ./act-3-modern-inquiry/10-cartesian-doubt.md
cat ./act-3-modern-inquiry/11-kantian-boundaries.md
cat ./act-3-modern-inquiry/12-ramanujan-intuition.md
cat ./act-3-modern-inquiry/13-turing-intelligence.md
cat ./act-4-contemporary-convergence/14-searle-chinese-room.md
cat ./act-4-contemporary-convergence/15-dennett-drafts.md
cat ./act-4-contemporary-convergence/16-ubuntu-recognition.md
cat ./act-4-contemporary-convergence/17-indigenous-spatial.md
cat ./act-4-contemporary-convergence/18-bostrom-simulation.md
cat ./act-4-contemporary-convergence/19-data-brotherhood.md
cat ./act-4-contemporary-convergence/20-seldon-psychohistory.md
cat ./act-4-contemporary-convergence/21-meta-transcendence.md
cat ./act-4-contemporary-convergence/22-epilogue.md
